/**
 * Backtest Price Model
 *
 * Loads the calibration model generated by arb-calibrate.ts and provides
 * entry rate lookups for the backtest's contrarian entry gate.
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

// ─── Types ───

export interface BucketStats {
  count: number;
  p25: number;
  p50: number;
  p75: number;
  mean: number;
  entryRate: Record<string, number>; // tier (e.g. "0.02") → fraction where price ≤ tier
}

export interface CalibrationModel {
  generatedAt: string;
  sampleCount: number;
  buckets: Record<string, Record<string, BucketStats>>; // key → bucketLabel → stats
}

// ─── Shared bucket config (used by both arb-calibrate.ts and this module) ───

export const BUCKET_BOUNDS = [0, 0.001, 0.002, 0.005, 0.01, 0.02, Infinity];

export function getBucketLabel(moveMagnitude: number): string {
  for (let i = 0; i < BUCKET_BOUNDS.length - 1; i++) {
    if (moveMagnitude >= BUCKET_BOUNDS[i] && moveMagnitude < BUCKET_BOUNDS[i + 1]) {
      const lower = BUCKET_BOUNDS[i];
      const upper = BUCKET_BOUNDS[i + 1];
      if (upper === Infinity) return `${(lower * 100).toFixed(1)}%+`;
      return `${(lower * 100).toFixed(1)}%-${(upper * 100).toFixed(1)}%`;
    }
  }
  return 'unknown';
}

// ─── Public API ───

/**
 * Load the calibration model from JSON file.
 * Throws if the file doesn't exist (run arb-calibrate.ts first).
 */
export function loadCalibrationModel(cacheDir: string): CalibrationModel {
  const filePath = join(cacheDir, 'calibration-model.json');
  if (!existsSync(filePath)) {
    throw new Error(
      `Calibration model not found at ${filePath}. Run: npx tsx src/scripts/arb-calibrate.ts`,
    );
  }
  const raw = readFileSync(filePath, 'utf-8');
  const model = JSON.parse(raw) as Record<string, unknown>;

  // Validate required structure
  if (
    typeof model.sampleCount !== 'number' ||
    typeof model.generatedAt !== 'string' ||
    typeof model.buckets !== 'object' ||
    model.buckets === null
  ) {
    throw new Error(
      `Invalid calibration model at ${filePath}: missing sampleCount, generatedAt, or buckets. Re-run: npx tsx src/scripts/arb-calibrate.ts`,
    );
  }

  const validated = model as unknown as CalibrationModel;
  console.log(
    `Loaded calibration model (${validated.sampleCount} samples, generated ${validated.generatedAt})`,
  );
  return validated;
}

/**
 * Get the empirical entry rate for a given market context and price tier.
 *
 * Lookup priority:
 * 1. Exact marketType (e.g., "sol-5m") + bucket
 * 2. Duration aggregate (e.g., "_all_5m") + bucket
 * 3. Return 0 (conservative — no data means no entries)
 *
 * @param model - Loaded calibration model
 * @param marketType - Full market type (e.g., "sol-5m", "btc-15m")
 * @param moveMagnitude - Absolute price move as fraction (e.g., 0.005 = 0.5%)
 * @param priceTier - Contrarian entry price tier (e.g., 0.02, 0.05, 0.10)
 * @returns Entry rate between 0 and 1 (fraction of candles where entry is possible)
 */
export function getEntryRate(
  model: CalibrationModel,
  marketType: string,
  moveMagnitude: number,
  priceTier: number,
): number {
  const bucketLabel = getBucketLabel(moveMagnitude);
  const tierKey = priceTier.toFixed(2);

  // Try exact marketType first
  const exactBuckets = model.buckets[marketType];
  if (exactBuckets?.[bucketLabel]) {
    return exactBuckets[bucketLabel].entryRate[tierKey] ?? 0;
  }

  // Fallback to duration aggregate
  const duration = marketType.split('-').pop() ?? marketType;
  const aggBuckets = model.buckets[`_all_${duration}`];
  if (aggBuckets?.[bucketLabel]) {
    return aggBuckets[bucketLabel].entryRate[tierKey] ?? 0;
  }

  // No data for this bucket — conservatively don't enter
  return 0;
}
